name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Rust setup
        run: rustup toolchain install stable --profile minimal

      - name: Cargo Clippy
        run: cargo clippy -- -D warnings

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Rust setup
        run: rustup toolchain install stable --profile minimal

      - name: Cargo Format
        run: cargo fmt --all -- --check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Rust setup
        run: rustup toolchain install stable --profile minimal

      - name: Cargo Test
        run: cargo test
